### ISSUE TITLE
[Documentation] READMEs in the src/ folder lack English descriptions

### ISSUE THREAD

**Issue by pradeeban** [ZacharyJia/opsdn#2]
The module-level READMEs in the src folder are in Chinese.

https://github.com/ZacharyJia/opsdn/tree/master/src/dll-bridge

https://github.com/ZacharyJia/opsdn/tree/master/src/models

Is there a chance to include the English translations as part of the README.

That will help us understand and appreciate the context and contribution of the framework better.

**Comment by pradeeban** [comment]
Fixed now.

**Comment by danielskatz** [comment]
note: this was part of https://github.com/openjournals/joss-reviews/issues/4815
