### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by pradeeban** [ZacharyJia/opsdn#5]
Do you have clear guidelines for third parties wishing to 
1) Contribute to the software 
2) Report issues or problems with the software 
3) Seek support?

A contributing.md or a wiki page addressing the above should help.

**Comment by danielskatz** [comment]
note: this is part of https://github.com/openjournals/joss-reviews/issues/4815

**Comment by ZacharyJia** [comment]
Done with #7 and d8b0cb1

**Comment by pradeeban** [comment]
This is great.
