### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by pradeeban** [ZacharyJia/opsdn#6]
Do/Can you have automated tests or sufficiently documented manual steps to verify the functionality?

Please let me know if you have documentation somewhere for the manual steps (or point me to the automated tests).

It will be good to document such steps, if no automated tests available.

**Comment by danielskatz** [comment]
note: this is part of https://github.com/openjournals/joss-reviews/issues/4815

**Comment by danielskatz** [comment]
Note that the JOSS criterion for tests is in https://joss.readthedocs.io/en/latest/review_criteria.html#tests

**Comment by ZacharyJia** [comment]
Hi @pradeeban and @danielskatz ,

Thanks for pointing this out. As it is really hard to make automated tests for OPNET, I added a [Functionality Check manual](https://github.com/ZacharyJia/opsdn/blob/master/docs/functionality-check-manual.md) for you to check OPSDN's features.

Hope this will help.

**Comment by pradeeban** [comment]
This documentation/manual is OK, as per the JOSS criterion for tests, especially considering the difficulty in creating automated tests for frameworks such as OPNET. I close this issue as fixed.
